# Metadata for your course

title: My awesome course. # a name for your Learning Lab course
tagline: A super awesome course.  # a short description for your Learning Lab course, displayed on the course catalog
description: Check out my awesome course. # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: my-awesome-course # the name of the repository when it is created for the learner
  repo: false # the name of the template repository from which to clone for the learner

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: createIssue
  body: welcome.md
  title: Welcome
# the type of action, full list at https://github.github.com/learning-lab-equipment/#/actions/
  # some actions require additional options, those should appear below `type:`
  # you can execute multiple actions in the `before` block

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
- title: Comment on an issue # the title of the step, shown to the learner in the course progress page
  description: Drop a comment # the event that will trigger the actions to be executed, full list at https://developer.github.com/v3/activity/events/types/
  event: issue_comment.created # a list of the actions that will occur when the step is triggered by an event
  actions:
  - type: respond
    with: you-did-it.md
  # the type of action, full list at https://github.github.com/learning-lab-equipment/#/actions/
  # some actions require additional options, those should appear below `type:`
  # you can execute multiple actions in the `before` block
  #
  # - type:
  #   option:
  #
  # - type:
  #   option:
